#!/usr/bin/env bash
#
# Pure-bash video manifest generator.
# Scans Videos/<YEAR>/ for videos + videos.json and writes data/video-manifest.js.
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
VIDEOS_DIR="$REPO_ROOT/Videos"
OUTPUT="$REPO_ROOT/data/video-manifest.js"
VIDEO_RE='\.(mp4|webm|mov|avi|ogv)$'
THUMB_RE='\.(jpg|jpeg|png|webp|avif)$'

if [ ! -d "$VIDEOS_DIR" ]; then
  echo "Error: Videos/ directory not found." >&2
  exit 1
fi

# Collect year directories, newest first
years=()
for d in "$VIDEOS_DIR"/*/; do
  dirname=$(basename "$d")
  if [[ "$dirname" =~ ^[0-9]{4}$ ]]; then
    years+=("$dirname")
  fi
done
IFS=$'\n' years=($(printf '%s\n' "${years[@]}" | sort -r)); unset IFS

# Start building manifest array
entries=""
added_srcs=""

for year in "${years[@]}"; do
  year_dir="$VIDEOS_DIR/$year"
  [ -d "$year_dir" ] || continue

  # 1. Read videos.json if present (for YouTube embeds / custom metadata)
  json_file="$year_dir/videos.json"
  if [ -f "$json_file" ]; then
    # Parse simple JSON array of objects with title, src, thumbnail
    # Using a lightweight approach: extract fields per entry
    entry_count=$(grep -c '"src"' "$json_file" 2>/dev/null) || true
    if [ "$entry_count" -gt 0 ]; then
      # Use python3 if available for reliable JSON parsing, else simple grep
      if command -v python3 &>/dev/null; then
        python3 -c "
import json, sys
with open('$json_file') as f:
    data = json.load(f)
if isinstance(data, list):
    for item in data:
        src = item.get('src', '')
        title = item.get('title', '')
        thumb = item.get('thumbnail', '')
        print(f'{src}\t{title}\t{thumb}')
" 2>/dev/null | while IFS=$'\t' read -r src title thumb; do
          [ -z "$src" ] && continue
          # Derive title from filename if empty
          if [ -z "$title" ]; then
            title=$(basename "$src" | sed 's/\.[^.]*$//' | tr '_-' ' ' | sed 's/  */ /g')
          fi
          if [ -z "$thumb" ] || [ "$thumb" = "null" ]; then
            thumb="null"
          else
            thumb="\"$thumb\""
          fi
          if [ -n "$entries" ]; then
            entries="$entries,"
          fi
          entries="$entries
  {
    \"title\": \"$title\",
    \"src\": \"$src\",
    \"thumbnail\": $thumb,
    \"year\": \"$year\"
  }"
          added_srcs="$added_srcs $src"
        done
      fi
    fi
  fi

  # 2. Scan for local video files
  for vid in "$year_dir"/*; do
    [ -f "$vid" ] || continue
    fname=$(basename "$vid")
    [[ "$fname" =~ $VIDEO_RE ]] || continue
    # Skip hidden files
    [[ "$fname" == .* ]] && continue

    full_src="Videos/$year/$fname"

    # Skip if already added via videos.json
    if echo "$added_srcs" | grep -qF "$full_src"; then
      continue
    fi

    # Derive title from filename
    title=$(echo "$fname" | sed 's/\.[^.]*$//' | tr '_-' ' ' | sed 's/  */ /g')

    # Look for matching thumbnail
    thumb="null"
    base="${fname%.*}"
    for t in "$year_dir"/*; do
      [ -f "$t" ] || continue
      tname=$(basename "$t")
      if [[ "$tname" =~ $THUMB_RE ]]; then
        tbase="${tname%.*}"
        if [ "$tbase" = "$base" ]; then
          thumb="\"Videos/$year/$tname\""
          break
        fi
      fi
    done

    if [ -n "$entries" ]; then
      entries="$entries,"
    fi
    entries="$entries
  {
    \"title\": \"$title\",
    \"src\": \"$full_src\",
    \"thumbnail\": $thumb,
    \"year\": \"$year\"
  }"
  done
done

# Count entries
count=0
if [ -n "$entries" ]; then
  count=$(echo "$entries" | grep -c '"title"' || echo 0)
fi

# Write output
cat > "$OUTPUT" <<ENDOFFILE
/**
 * video-manifest.js
 * Auto-generated by generate-video-manifest.sh — do not edit manually.
 */

const VIDEO_MANIFEST = [$entries
];
ENDOFFILE

echo "  ✓ Wrote video-manifest.js ($count videos, ${#years[@]} years)"
