#!/usr/bin/env bash
#
# Pure-bash gallery manifest generator.
# Scans Galleries/<YEAR>/ for images and writes data/gallery-manifest.js.
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
GALLERIES_DIR="$REPO_ROOT/Galleries"
OUTPUT="$REPO_ROOT/data/gallery-manifest.js"
SUPPORTED_RE='\.(jpg|jpeg|png|gif|webp|avif)$'

if [ ! -d "$GALLERIES_DIR" ]; then
  echo "Error: Galleries/ directory not found." >&2
  exit 1
fi

# Collect year directories (4-digit names), newest first
years=()
for d in "$GALLERIES_DIR"/*/; do
  dirname=$(basename "$d")
  if [[ "$dirname" =~ ^[0-9]{4}$ ]]; then
    years+=("$dirname")
  fi
done
IFS=$'\n' years=($(printf '%s\n' "${years[@]}" | sort -r)); unset IFS

# Start building the manifest
manifest="{"
first_year=1
all_photos=()

for year in "${years[@]}"; do
  year_dir="$GALLERIES_DIR/$year"
  [ -d "$year_dir" ] || continue

  # Find matching images, sorted
  images=()
  for img in "$year_dir"/*; do
    [ -f "$img" ] || continue
    fname=$(basename "$img")
    if [[ "$fname" =~ $SUPPORTED_RE ]]; then
      images+=("$fname")
    fi
  done
  IFS=$'\n' images=($(printf '%s\n' "${images[@]}" | sort)); unset IFS

  # Skip empty years
  [ ${#images[@]} -eq 0 ] && continue

  # Build JSON array for this year
  entries=""
  for img in "${images[@]}"; do
    rel="Galleries/$year/$img"
    all_photos+=("$rel")
    if [ -n "$entries" ]; then
      entries="$entries,"
    fi
    entries="$entries\n    \"$rel\""
  done

  if [ "$first_year" -eq 1 ]; then
    first_year=0
  else
    manifest="$manifest,"
  fi
  manifest="$manifest\n  \"$year\": [$entries\n  ]"
done

# Close the manifest object
manifest="$manifest\n}"

# Build preview (first 6 photos)
preview="["
count=0
for photo in "${all_photos[@]}"; do
  if [ "$count" -ge 6 ]; then
    break
  fi
  if [ "$count" -gt 0 ]; then
    preview="$preview,"
  fi
  preview="$preview\n  \"$photo\""
  count=$((count + 1))
done
preview="$preview\n]"

# Write the output file
cat > "$OUTPUT" <<ENDOFFILE
/**
 * gallery-manifest.js
 * Auto-generated by generate-gallery-manifest.sh — do not edit manually.
 */

const GALLERY_MANIFEST = $(echo -e "$manifest");

const GALLERY_PREVIEW = $(echo -e "$preview");
ENDOFFILE

total=${#all_photos[@]}
echo "  ✓ Wrote gallery-manifest.js ($total photos, ${#years[@]} years)"
